#!/bin/bash
# install.sh — 把 scripts/ 下的通用工具装成 /usr/local/bin/ 下的薄壳 launcher。
#
# 为什么不直接 PATH=${PROJECT_ROOT}/scripts:$PATH？
#   - 如果项目根挂在 sshfs / NTFS 上，chmod +x 不生效，PATH 找到了也没法直接执行
#   - 改用：/usr/local/bin/<name> 是 Linux 本地 fs 上的薄壳脚本（仅 `exec bash <target> "$@"`），
#     真正的逻辑、防呆、配置全在 ${PROJECT_ROOT}/scripts/，重装服务器 `bash scripts/install.sh` 即可恢复。
#
# 用法：
#   bash scripts/install.sh
# 之后任何 shell（包括 Claude 非交互 Bash）都能直接调工具名。
# 幂等：重复跑只会覆盖 launcher，不会重复污染。

set -e

install_launcher() {
  local name="$1"
  local target="$2"
  local launcher="/usr/local/bin/$name"

  cat > "$launcher" <<EOF
#!/bin/bash
# Auto-generated by ${PROJECT_ROOT}/scripts/install.sh — DO NOT EDIT.
# 真正的逻辑在 $target，本文件仅做转发。
exec bash $target "\$@"
EOF
  chmod +x "$launcher"
  echo "✅ 安装 $launcher → exec bash $target"
}

install_launcher tspawn        ${PROJECT_ROOT}/scripts/tspawn
install_launcher tpush         ${PROJECT_ROOT}/scripts/tpush
install_launcher revive        ${PROJECT_ROOT}/scripts/revive
install_launcher jsonl-status  ${PROJECT_ROOT}/scripts/jsonl-status
install_launcher myjsonl       ${PROJECT_ROOT}/scripts/myjsonl
install_launcher work_log      ${PROJECT_ROOT}/scripts/work_log

# ----- tmux bell 透传配置（幂等追加到 ~/.tmux.conf） -----
#
# 为什么需要：Claude Code 的 Notification hook 发 BEL（\a）到 /dev/tty，
# tmux 默认会"吞掉" bell（bell-action 默认 none），导致外层终端（Tabby /
# iTerm / Windows Terminal）的标签页看不到红点提示。所以需要：
#   - bell-action any：所有 window 收到 bell 都透传给 client（外层终端）
#   - visual-bell off：发真 BEL 字符，不改用闪烁（闪烁的话 BEL 就不发了）
#
# 幂等：grep 检查标记行，已存在就不重复追加。
tmux_conf="$HOME/.tmux.conf"
tmux_marker="# bell 透传到外层终端（Tabby / iTerm / Windows Terminal 标签页红点提示）"
if [ ! -f "$tmux_conf" ] || ! grep -qF "$tmux_marker" "$tmux_conf"; then
  cat >> "$tmux_conf" <<EOF

$tmux_marker
# 由 ${PROJECT_ROOT}/scripts/install.sh 维护，重装服务器幂等恢复
set -g bell-action any
set -g visual-bell off
EOF
  echo "✅ 追加 tmux bell 配置到 $tmux_conf"
  # 如果在 tmux 里跑 install.sh，顺手 reload 让现存 session 立即生效
  if [ -n "$TMUX" ]; then
    tmux source "$tmux_conf" 2>/dev/null && echo "✅ tmux source 已 reload"
  fi
else
  echo "✓ $tmux_conf 已有 bell 配置，跳过"
fi

# ----- tmux history-limit 调大（幂等追加，独立 marker） -----
#
# 为什么需要：cc 长跑刷量大 + capture-pane 调试常需回看，默认 2000 行翻几下到顶。
# 50000 行内存代价 ~50MB/pane，服务器富裕可接受。
#
tmux_history_marker="# history-limit 调大（cc 长跑 + capture-pane 调试回看）"
if [ ! -f "$tmux_conf" ] || ! grep -qF "$tmux_history_marker" "$tmux_conf"; then
  cat >> "$tmux_conf" <<EOF

$tmux_history_marker
# 由 ${PROJECT_ROOT}/scripts/install.sh 维护，重装服务器幂等恢复
set -g history-limit 50000
EOF
  echo "✅ 追加 tmux history-limit 配置到 $tmux_conf"
  if [ -n "$TMUX" ]; then
    tmux source "$tmux_conf" 2>/dev/null && echo "✅ tmux source 已 reload"
  fi
  echo "ℹ️  现存 pane 仍是旧 history-limit；新开 pane 起用 50000"
else
  echo "✓ $tmux_conf 已有 history-limit 配置，跳过"
fi

# ----- 关右键 display-menu 防误触 Kill pane / Kill window -----
#
# 为什么需要：tmux 3.6a 默认在 root table 绑了 6 个 MouseDown3*（右键），点出
# 的 menu 含 "Kill pane" / "Kill window" 项。容易误触把 cc worker 进程杀掉，
# 需要 cc --resume 救活。unbind 6 个右键 binding 关菜单。
#
# 副作用：失去右键 Split / Swap / Mark 等便利项。
# 不影响：左键 select-pane / 中键 paste / 拖选 copy-mode / 拖 border resize /
#         滚轮 / 双击 select-word / 三击 select-line / 点 status 切 window。
# Kill 仍能通过 prefix + x / & 触发（有意识 keystroke 不易误触）。
#
tmux_rightclick_marker="# 关右键 display-menu 防误触 Kill pane / Kill window"
if [ ! -f "$tmux_conf" ] || ! grep -qF "$tmux_rightclick_marker" "$tmux_conf"; then
  cat >> "$tmux_conf" <<TMUX_RCEOF

$tmux_rightclick_marker
# 由 ${PROJECT_ROOT}/scripts/install.sh 维护，重装服务器幂等恢复
unbind -T root MouseDown3Pane
unbind -T root MouseDown3Status
unbind -T root MouseDown3StatusLeft
unbind -T root M-MouseDown3Pane
unbind -T root M-MouseDown3Status
unbind -T root M-MouseDown3StatusLeft
TMUX_RCEOF
  echo "✅ 追加 tmux 关右键菜单配置到 $tmux_conf"
  if [ -n "$TMUX" ]; then
    tmux source "$tmux_conf" 2>/dev/null && echo "✅ tmux source 已 reload"
  fi
else
  echo "✓ $tmux_conf 已有关右键菜单配置，跳过"
fi

echo ""
echo "✅ 全部就绪。验证："
echo "   which tspawn tpush revive jsonl-status myjsonl work_log"
echo "   jsonl-status                # 全部 session（除管家 ${BUTLER_SESSION}）"
echo "   myjsonl                     # 自查 cc jsonl UUID"
echo "   tmux show-options -g | grep -E 'bell-action|visual-bell|history-limit'"
